In [1]:
import numpy as np

a= np.random.randn(5)


In [2]:
print(a)

[ 1.33656232 -1.40864613  1.34749132 -0.13112865 -0.37928692]


In [3]:
print(a.shape) #1순위 벡터

(5,)


In [4]:
print(a.T) #a 와 같다

[ 1.33656232 -1.40864613  1.34749132 -0.13112865 -0.37928692]


In [5]:
print(np.dot(a,a.T))

5.747468911745407


In [6]:
#1순위 배열을 피하는 방법

a = np.random.randn(5,1)
print(a)

[[-1.04008497]
 [ 0.37477898]
 [ 0.94934975]
 [ 0.2137811 ]
 [-0.75042089]]


In [7]:
print(a.T)

[[-1.04008497  0.37477898  0.94934975  0.2137811  -0.75042089]]


In [9]:
print(np.dot(a,a.T))

[[ 1.08177674 -0.38980198 -0.98740441 -0.22235051  0.78050149]
 [-0.38980198  0.14045928  0.35579633  0.08012066 -0.28124197]
 [-0.98740441  0.35579633  0.90126495  0.20295303 -0.71241188]
 [-0.22235051  0.08012066  0.20295303  0.04570236 -0.1604258 ]
 [ 0.78050149 -0.28124197 -0.71241188 -0.1604258   0.56313151]]
